baseURL = "http://hitjim.com/"
defaultContentLanguage = "en"
languageCode = "en"
title = "hit jim dot com"

theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"
  defaultTheme = "dark"
  description = "Jim Rice's personal website."
  keywords = ["tech", "development", "gamedev", "productivity", "model aviation", "cautious optimism?"]

[params.app]
  title = "hit jim dot com"

[params.footer]
  hugo = false

[params.home]
  [params.home.profile]
    gravatarEmail = "hitjim@gmail.com"
    title = "Jim Rice"
    disclaimer = "'Sucking at something is the first step towards being sorta good at something' - Jake the Dog"

[params.social]
  GitHub = "hitjim"
  Twitter = "jiiimbot"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/Categories/"
    weight = 3

[markup]
  [markup.highlight]
    noClasses = false
