[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.75.0-DEV/extended"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.75.0-DEV/extended"
